# Generated by Django 6.0.7 on 2026-07-18 12:57

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('organizations', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=550, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('requirements', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('opportunity_type', models.CharField(choices=[('jobs', 'Jobs'), ('scholarships', 'Scholarships'), ('internships', 'Internships'), ('fellowships', 'Fellowships'), ('grants', 'Grants'), ('competitions', 'Competitions'), ('volunteer', 'Volunteering'), ('procurement', 'Procurement'), ('training', 'Training'), ('conference', 'Conference'), ('exchange', 'Exchange Program'), ('events', 'Events'), ('research', 'Research'), ('business', 'Business'), ('tender', 'Tender'), ('consultancy', 'Consultancy'), ('ngo_jobs', 'NGO Jobs'), ('government_jobs', 'Government Jobs'), ('others', 'Others')], max_length=20)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive'), ('any', 'Any Level')], default='any', max_length=20)),
                ('education_level', models.CharField(choices=[('high_school', 'High School'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('any', 'Any'), ('other', 'Other')], default='any', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('remote', models.BooleanField(default=False)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('salary_period', models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One-time')], max_length=20)),
                ('funding_amount', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('application_link', models.URLField(blank=True)),
                ('application_email', models.EmailField(blank=True, max_length=254)),
                ('application_instructions', models.TextField(blank=True)),
                ('max_users', models.PositiveIntegerField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('urgent', models.BooleanField(default=False)),
                ('sponsored', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('bookmark_count', models.PositiveIntegerField(default=0)),
                ('application_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='categories.category')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='organizations.organization')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_opportunities', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'db_table': 'opportunities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['opportunity_type'], name='opportuniti_opportu_b8dd5f_idx'), models.Index(fields=['status'], name='opportuniti_status_019aa6_idx'), models.Index(fields=['featured'], name='opportuniti_feature_bcc85e_idx'), models.Index(fields=['deadline'], name='opportuniti_deadlin_a61419_idx'), models.Index(fields=['country'], name='opportuniti_country_42165f_idx'), models.Index(fields=['organization'], name='opportuniti_organiz_97a57f_idx'), models.Index(fields=['status', 'opportunity_type'], name='opportuniti_status_d1355d_idx')],
            },
        ),
    ]
