# Generated by Django 6.0.7 on 2026-07-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='employment_type',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='applications_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='bookmarks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='country',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='deadline',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive'), ('any', 'Any')], default='any', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], max_length=20),
        ),
    ]
