# Generated by Django 6.0.7 on 2026-07-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.CharField(blank=True, help_text='Alternative text if author has no user account', max_length=150),
        ),
    ]
