# Generated by Django 6.0.7 on 2026-07-18 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('viewed', 'Viewed'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='application_resumes/')),
                ('portfolio_url', models.URLField(blank=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='application_user_id_4cfcce_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'opportunity'), name='unique_application_per_user')],
            },
        ),
    ]
