# Generated by Django 6.0.7 on 2026-07-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(),
        ),
    ]
